### ISSUE TITLE
Open folder (RC 1.4.8) 

### ISSUE THREAD

**Issue by toteph42** [random-cuber/contextmenu_folder#16]
Please see https://github.com/roundcube/roundcubemail/issues/7591#issuecomment-688654827

As a small give back, you'll find attached German localization

[de_DE.zip](https://github.com/random-cuber/contextmenu_folder/files/5187582/de_DE.zip)

**Comment by Andrei-Pozolotin** [comment]
1. please submit a PR
2. German localization is already present, is there problem with it?

**Comment by toteph42** [comment]
1. I opened this issue. Do expect something different?
2. No problem with localization. Sorry for my confusion.

**Comment by mkrumbholz** [comment]
I think @syncgw meant the referenced issue.
With this folder jumping:
![FolderJumping](https://user-images.githubusercontent.com/31690023/97156024-6ac7f080-1776-11eb-8069-79a16e856baa.gif)

roundcube version 1.4.9
Design: Larry
Layout: list (no mail preview)

If you disable "remember_mailbox" and "remember_message", the problem is gone.

**Comment by Andrei-Pozolotin** [comment]
obsolete
